#!/bin/bash
# recon-GOD-v15.sh - FULL RECON + PORTS + OS + VULNS + WEAK STRONG
# Author: DevSec Pro | 2025

set -euo pipefail
G="\033[0;32m"; R="\033[0;31m"; Y="\033[1;33m"; C="\033[0;36m"; N="\033[0m"
msg() { echo -e "${2:-$G}[GOD] $1$N"; }

DOMAIN="$1"
WORKDIR="$HOME/GOD-v15-$DOMAIN-$(date +%s)"
mkdir -p "$WORKDIR"/{subs,live,urls,params,ports,vulns,report} && cd "$WORKDIR"

# Auto-Install
install() {
    [[ -z "$(command -v $1)" ]] && {
        msg "Installing $1..." "$Y"
        go install "$2" 2>/dev/null || pip install "$2" 2>/dev/null || true
    }
}
install httpx github.com/projectdiscovery/httpx/cmd/httpx@latest
install nuclei github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
install naabu github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
install nmap nmap
install gf github.com/tomnomnom/gf@latest
nuclei -update-templates &>/dev/null

# 1. Subdomains
msg "Subdomains..."
{
    subfinder -d "$DOMAIN" -silent
    amass enum -passive -d "$DOMAIN" | grep -oE "[a-zA-Z0-9.-]+\.$DOMAIN"
    assetfinder --subs-only "$DOMAIN"
    gau "$DOMAIN" --subs
} | sort -u > subs.txt
msg "Subdomains: $(wc -l < subs.txt)"

# 2. Live URLs
msg "Live Probing..."
sed 's/^/https:\/\//' subs.txt | httpx -silent -sc -title > live.txt
grep -E "200|301|302" live.txt | awk '{print $1}' > live_urls.txt
msg "Live: $(wc -l < live_urls.txt)"

# 3. URL Collection
msg "Crawling URLs..."
gau "$DOMAIN" --subs > urls/gau.txt
katana -list live_urls.txt -silent -d 3 -o urls/katana.txt
cat live_urls.txt urls/gau.txt urls/katana.txt | sort -u > urls/all.txt
msg "Total URLs: $(wc -l < urls/all.txt)"

# 4. Parameters
msg "Parameter Hunting..."
gf xss urls/all.txt > params/xss.txt
gf sqli urls/all.txt > params/sqli.txt
gf lfi urls/all.txt > params/lfi.txt
head -50 live_urls.txt | paramspider -o params/paramspider.txt --quiet
msg "Params: $(find params -type f -name "*.txt" -exec wc -l {} + | tail -1 | awk '{print $1}')"

# 5. PORT SCAN + OS + SERVICES + VULNS
msg "Port Scanning + OS + Services..."
naabu -list live_urls.txt -p 1-1000 -o ports/open.txt
nmap -iL ports/open.txt -sV -O --script vuln -oX ports/nmap.xml -oN ports/nmap.txt
msg "Ports: $(wc -l < ports/open.txt)"

# 6. NUCLEI FULL (Critical + High + Medium + Low)
msg "Nuclei FULL Scan (All Severities)..."
nuclei -l urls/all.txt -severity critical,high,medium,low -o vulns/all.txt -c 200
msg "Vulns: $(wc -l < vulns/all.txt)"

# 7. OS & Service Summary
msg "OS & Services Summary..."
OS=$(grep -oP '<osmatch name="\K[^"]+' ports/nmap.xml | head -1 || echo "Unknown")
SERVICE=$(grep -oP '<service name="\K[^"]+' ports/nmap.xml | head -1 || echo "Unknown")
VERSION=$(grep -oP '<service product="\K[^"]+' ports/nmap.xml | head -1 || echo "Unknown")

# 8. HTML Report (Beautiful + Professional)
cat > report/GOD.html <<EOF
<!DOCTYPE html>
<html><head><title>GOD v15 - $DOMAIN</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<style>body{background:#000;color:#0f0;font-family:monospace}</style></head>
<body class="p-5">
<div class="container text-center">
<h1 class="text-success">RECON GOD v15</h1>
<h2>$DOMAIN</h2>
<pre>Subdomains: $(wc -l < subs.txt)</pre>
<pre>Live URLs: $(wc -l < live_urls.txt)</pre>
<pre>Total URLs: $(wc -l < urls/all.txt)</pre>
<pre>Parameters: $(find params -type f -name "*.txt" -exec wc -l {} + | tail -1 | awk '{print $1}')</pre>
<pre>Open Ports: $(wc -l < ports/open.txt)</pre>
<pre>OS: $OS</pre>
<pre>Service: $SERVICE $VERSION</pre>
<pre>Vulnerabilities: $(wc -l < vulns/all.txt)</pre>
<hr>
<h3 class="text-danger">Top Vulnerabilities (All Severities)</h3>
<pre>$(head -15 vulns/all.txt)</pre>
<p>Generated by <b>GOD v15</b> • $(date)</p>
</div></body></html>
EOF

msg "DONE! Open Report:" "$G"
echo "firefox $WORKDIR/report/GOD.html"
